### ISSUE TITLE
Allow user (DOHMH) to control label positioning of features based on zoom level

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/pods#2]
DOHMH should be able to control the label position of features based on zoom level. Please verify we have testing in place for this requirement. 

**Background**
DOHMH POD facilities were initially placed based off of population density and facility feasibility. As such, dense areas of NYC contain POD sites that are in close proximity of each other. This leads to labels that can overlap due to how the underlying code and DOHMH preferences for labeling have been placed. Designating labeling based on the standard zoom levels would be ideal. 

**March 2020 Implementation Notes:**
DOHMH can specify the cardinal direction of labels at each zoom level. In the existing REST service (and new csv), DOHMH may update the “labelpos” field with a space-delimited list where each index of the list corresponds to a zoom level for up to 8 zoom levels (14-21). 

DOHMH can specify all zoom levels with a space-delimited list – 

Ex. labelpos value: E E N N N N N N 

Where labels at zoom level 14-15 will be placed east and labels at zoom level 16 – 21 would be placed north OR only specify specific zoom levels and DOITT will use default east where zoom not provided.  

Ex. labelpos value: E E N N  

Where labels at zoom level 14 – 15 would be placed east, 16-17 placed north, and all remaining zoom levels placed east.  

Note: Since this is based on an index, DOHMH would need to provide consecutive values. For example, if only zoom level 16 needs to be specified, DOHMH would need to provide label direction information for 14 and 15 as well. All other zooms after 16 would default to “E”

**Comment by cmenedes** [comment]
We added this in the last iteration. I'll make sure it's properly tested though.
See commit df8890ac2c60f615701193d081146d6948a575d7

**Comment by cmenedes** [comment]
@ekamptner 
This is working fine. The issue can be closed.
ex: this feature has LabelPos set to E S N W N E
See gif below:
![labelpos](https://user-images.githubusercontent.com/11576888/88411088-548c4c00-cda5-11ea-8798-940d7702a098.gif)

**Comment by ekamptner** [comment]
Confirmed with DOHMH. closing
